### ISSUE TITLE
not working with roundcube 1.1.0

### ISSUE THREAD

**Issue by plemo** [elm/Roundcube-SMTP-per-Identity-Plugin#7] opened 2015-02-18 17:11 UTC
Since update to roundcube 1.1.0 the plugin identity_smtp isn't functioning anymore. At sending, an error occurs ("SMTP error (-1)"). Connection failed.

**Comment by elm** [comment] 2015-02-23 08:59
I was on vacation and will have a look at this.

**Comment by elm** [comment] 2015-03-22 13:03
Can you try to reenter and resave the identities smtp password?

**Comment by plemo** [comment] 2015-03-24 14:16
I did. It's a totally new installation of roundcube 1.1.0, so all information for the identity smtp plugin has been reentered. I checked already type errors, everything is identically typed in as in my old installation. SMTP error (-1) keeps returning.
Also there isn't any info in the smtp log when I turn on this log, so I guess the smtp function within roundcube isn't even started correctly.

**Comment by elm** [comment] 2015-03-24 14:27
Do you have a default smtp server in your config? Here https://github.com/roundcube/roundcubemail/blob/4d9627c36a49918dbb5fe084173a01c6550ea790/program/lib/Roundcube/rcube.php#L1657 you can see that round cube does not invoke any smtp functions if no smtp server is set in the default config.

**Comment by plemo** [comment] 2015-03-27 15:12
Yes, I have. I configured the new roundcube 1.1.0 installation exactly like the old one (0.9.2), likewise the plugin. The error 'SMTP error (-1)' keeps returning, even though the configuration worked just fine in the old roundcube.
Can't the error be reproduced in other 1.1.0 installations?

**Comment by elm** [comment] 2015-03-27 15:20
I know of two roundcube 1.1.0 installations that are working with the plugin.

Do you have smtp_debug (https://github.com/roundcube/roundcubemail/blob/4d9627c36a49918dbb5fe084173a01c6550ea790/config/defaults.inc.php#L109) set to true and is the logs directory writeable by the user that runs roundcube? Maybe you can get some more output there.

**Comment by plemo** [comment] 2015-03-29 17:23
Yes, I did this already. The smtp log is activated and working, smtp without the plugin as well, and then smtp is logged correctly.
Whith the plugin turned on, nothing ends up in the smtp log, but there are three new lines in the error log with every try:

[29-Mar-2015 19:13:58 Europe/Berlin] ERROR: Die Wartezeit für die Verbindung ist abgelaufen (110)
[29-Mar-2015 19:13:58 Europe/Berlin] ERROR: Failed to connect socket: Die Wartezeit für die Verbindung ist abgelaufen ()
[29-Mar-2015 19:13:58 +0200]: <...> SMTP Error: Connection failed: Failed to connect socket: Die Wartezeit für die Verbindung ist abgelaufen in /var/www/webxx/html/roundcube/program/lib/Roundcube/rcube.php on line 1708 (POST /?_task=mail&_unlock=loadingxxx&_lang=en&_framed=1?_task=mail&_action=send)

(With the German parts meaning approx. 'Connection timed out'.)

Because of the timeout I have to add the information that the smtp servers I tried (different ones) all work fine and are accessable with different clients without an error.

**Comment by elm** [comment] 2015-03-31 11:47
Hmm, I have no idea what could cause this. You may have to get XDEBUG running and debug this yourself.

**Comment by thenktor** [comment] 2015-05-07 08:51
It is not working on my Roundcube 1.1.0 installation, too.
In sendmail log:
`[07-May-2015 08:45:32 +0000]: <xxxxxxxx> User xyz [192.168.x.y]; Message for test@gmail.com;`
In error log:
`PHP Error: Failed to load plugin file /srv/www/htdocs/rc/plugins/plugin_manager/plugin_manager.php in /srv/www/htdocs/rc/program/lib/Roundcube/rcube_plugin_api.php on line 198`

**Comment by elm** [comment] 2015-05-26 10:28
@thenktor This does not look like an error of this plugin but of the plugin_manager plugin. Also the smtp log would be useful (see my comment above, https://github.com/elm/Roundcube-SMTP-per-Identity-Plugin/issues/7#issuecomment-86972748 )

**Comment by danielmorlock** [comment] 2015-06-11 09:33
It seem's that the identities cannot be updated anymore since the hooks are not triggered with RC 1.1.0.

**Comment by sahne123** [comment] 2015-06-12 09:31
I can confirm that the plugin is still working. Just did a fresh install.

**Comment by danielmorlock** [comment] 2015-06-12 09:49
Me too. Works with Roundcubemail 1.1.1

**Comment by elm** [comment] 2015-06-12 09:51
Thank you. I close this issue. If there are still problems feel free to open a new issue.

**Closed by elm** 2015-06-12 09:51 UTC
